---
title: "Data Wrangling"
author: "Emily McNamara"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("~/Desktop/Almond Data Analytics Project 2020/Almond_Project_Data_Analytics")

library(tidyverse)
library(lubridate)
library(plyr)
```

```{r, data wrangling}

almonds.project.raw <- read.csv("./Data/Raw/Almond_Survey_Results_raw.csv")

colnames(almonds.project.raw)

almonds.project.CoverCrop.processed <- almonds.project.raw %>%
  select(Role.in.Operation:Regions, Total.Yield.Bearing.Acreage, Acre.Ranges, Cover.Crop.Grown:Cover.Crop.Incentives, Pollination:Age)

write.csv(almonds.project.CoverCrop.processed, row.names = FALSE, file = "./Data/Processed/Almond_Project_CoverCrop_Processed.csv")



almonds.project <- read.csv("./Data/Processed/Almond_Survey_Data_Project_Processed.csv")

almonds.numeric.project <- read.csv("./Data/Processed/Almond_Survey_Numeric_Answers_Processed.csv")

```
```{r, Data Wrangling}


# Read in raw almond survey response data
almonds.project.raw <- read.csv("./Data/Raw/Almond_Survey_Results_Raw.csv")

# Look at column names
#colnames(almonds.project.raw)

# Select column names that only apply to cover crop analysis

almonds.project.CC.processed <- almonds.project.raw %>%
  dplyr::select(Role.in.Operation:Regions, 
                Total.Yield.Bearing.Acreage, Acre.Ranges, 
                Cover.Crop.Grown:Cover.Crop.Incentives, Pollination:Age)


# Fill all empty cells in almonds.project.CC.processed with 'NA'
# Name 'almonds.CC'
almonds.CC <- almonds.project.CC.processed %>% mutate_all(na_if, "")


# Save new processed dataset
#write.csv(almonds.CC, row.names = FALSE, 
#file = "./Data/Processed/Almond_Project_CoverCrop_Processed.csv")



```


## Data Wrangling: Almond Survey Numeric Response Dataset
```{r}

# Read in almond survey numeric response data
almonds.numeric.raw <- read.csv("./Data/Raw/Almond_Survey_Numeric_Answers_Raw.csv")


# Look at column names
#colnames(almonds.numeric.raw)

# Choose columns for cover crop analyses that require numeric data

almonds.numeric <- almonds.numeric.raw %>%
  dplyr::select(Role.in.Operation, Regions, Total.Yield.Bearing, Cover.Crop.Grown, Age)

# Save new processed dataset
#write.csv(almonds.numeric, row.names = FALSE, 
#file = "./Data/Processed/Almond_Survey_Numeric_Answers_Processed.csv")


```

