---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "Web address for GitHub repository"
author: "Name"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}


# Set your working directory

setwd("~/Desktop/Almond Data Analytics Project 2020/Almond_Project_Data_Analytics")

getwd()

# Load your packages

library(tidyverse)
library(cowplot)
library(viridis)
library(RColorBrewer)
library(colormap)
library(ggplot2)
library(nlme)
library(nnet)
library(MASS) 
library(lme4)
library(boot)


# Set your ggplot theme

mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets


almonds.project <- read.csv("./Data/Processed/Almond_Survey_Cleaned_Official_Data_Project.csv")

almonds.numeric.project <- read.csv("./Data/Processed/Survey_numeric_answers_CLEANED.csv")
```


# Rationale and Research Questions
```{r, Research Questions}


```

\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
